//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Eclerx.RIteshKumar.Question._01.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class StudentRegistraion
    {
        public int StudentId { get; set; }
        public string UserId { get; set; }
        public string Password { get; set; }
        public Nullable<System.DateTime> DateOfBirth { get; set; }
        public Nullable<int> MobileNo { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
    }
}
